# <% require "dotenv"; Dotenv.load(".env") %>

service: demo-ruby-hanami
image: gambala/demo-ruby-hanami
servers:
  - <%= ENV["MAIN_SERVER_IP"] %>
proxy:
  ssl: false
  host: hanami.gambala.pro
  app_port: 2300
  healthcheck:
    interval: 10
    path: /plain
registry:
  server: ghcr.io
  username: gambala
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  clear:
    HANAMI_MAX_THREADS: 20
    HANAMI_WEB_CONCURRENCY: 0
aliases:
  shell: app exec --interactive --reuse "sh"
  logs: app logs -f
builder:
  arch: arm64
